In [3]:
import numpy as np

a = np.array([1,3,5])
print(a)
print(a.shape)

[1 3 5]
(3,)


In [8]:
tda = np.array([[1,2,3],[4,5,6] ])
print(tda.shape)
print(tda)
print(tda.dtype)

(2, 3)
[[1 2 3]
 [4 5 6]]
int64


In [29]:
ar2 = np.array([1,3.5,2], dtype = int)
print(ar2.dtype)
print(ar2)

int64
[1 3 2]


In [30]:
ar3 = np.array([[1,2],[3,4],[5,6]])
# add a column in 2nd row
print(ar3)

col = np.array([[0],[8],[0]])
# ar4 = np.array([ar3,col])

ar4 = np.append(ar3,col,axis = 1)

print(ar4)
ar4.reshape(3,3)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 0]
 [3 4 8]
 [5 6 0]]


array([[1, 2, 0],
       [3, 4, 8],
       [5, 6, 0]])

In [31]:
ar5 = np.linspace(0,1,10)
print(ar5)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [28]:
aa = np.arange(12).reshape(3, 4)